### ISSUE TITLE
显示查询出错

### ISSUE THREAD

**Issue by ccjk45415** [Gaylone/blhx_wiki#11]
开始
Loading page (1/2)
Rendering (2/2)
Done
结束
Loading page (1/2)
Rendering (2/2)
Done
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wulala\HoshinoBot\hoshino\modules\blhx_wiki\__init__.py", line 81, in send_ship_skin_or_info
    msg = "舰船信息\n" + MessageSegment.image("file:///" + SAVE_PATH + "/images/ship_info.png") \

**Comment by ccjk45415** [comment]
求大佬们帮帮忙呀

**Comment by Gaylone** [comment]
报错不完整

**Comment by ccjk45415** [comment]
> 报错不完整

可以给个联系方式吗 把详细内容给你

**Comment by ccjk45415** [comment]
这个好像是完整的吧
[2021-12-04 13:38:45,297 nonebot] INFO: Self: 248094548, Message -1016272056 from 2761890993@[群:819357415]: 'blhx 雪风'
[2021-12-04 13:38:45,297 blhx_wiki] INFO: Message -1016272056 triggered send_ship_skin_or_info by PrefixTrigger.
开始
Loading page (1/2)
Rendering (2/2)
Done
结束
Loading page (1/2)
Rendering (2/2)
Done
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wulala\HoshinoBot\hoshino\modules\blhx_wiki\__init__.py", line 81, in send_ship_skin_or_info
    msg = "舰船信息\n" + MessageSegment.image("file:///" + SAVE_PATH + "/images/ship_info.png") \
TypeError: can only concatenate str (not "MessageSegment") to str
[2021-12-04 13:38:48,013 nonebot] INFO: Message -1016272056 is ignored

**Comment by Gaylone** [comment]
截图扔上来呗

**Comment by ccjk45415** [comment]
![image](https://user-images.githubusercontent.com/76248184/144698808-56e8f5df-5d79-45a6-8705-8dbf63ccc87c.png)

**Comment by ccjk45415** [comment]
关于强度榜也出错了
[2021-12-04 13:40:53,415 nonebot] INFO: Self: 248094548, Message 761432676 from 2761890993@[群:819357415]: 'blhx 强度榜'
[2021-12-04 13:40:53,417 blhx_wiki] INFO: Message 761432676 triggered send_pve_recommendation by PrefixTrigger.
[2021-12-04 13:40:53,684 blhx_wiki] ERROR: <class 'TypeError'> occured when send_pve_recommendation handling message 761432676.
[2021-12-04 13:40:53,684 blhx_wiki] ERROR: can only concatenate str (not "MessageSegment") to str
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wulala\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\wulala\HoshinoBot\hoshino\service.py", line 218, in wrapper
    return await func(bot, event)
  File "C:\Users\Administrator\Desktop\wulala\HoshinoBot\hoshino\modules\blhx_wiki\__init__.py", line 128, in send_pve_recommendation
    msg += (div_text[i] + MessageSegment.image(file=str(div_list[i].find('img')['src'])) + "\n")
TypeError: can only concatenate str (not "MessageSegment") to str

**Comment by ccjk45415** [comment]
> 截图扔上来呗

关于强度榜这个 群里面是没给任何提示 只是在后台显示错误
![image](https://user-images.githubusercontent.com/76248184/144698950-6f676434-c108-43b1-8d7d-8525cef88c3e.png)

**Comment by Gaylone** [comment]
其实我很想说我这没问题，真是奇了怪了

**Comment by ccjk45415** [comment]
> 其实我很想说我这没问题，真是奇了怪了

![image](https://user-images.githubusercontent.com/76248184/144699067-9bf32444-770f-483c-8b86-4a6ae0c08139.png)
![image](https://user-images.githubusercontent.com/76248184/144699081-d39f269e-c84b-4220-b373-a792a7b61a92.png)
 查询皮肤什么的没什么问题 目前就发现强度榜和船的信息有问题

**Comment by Gaylone** [comment]
你把__init__.py里send_ship_skin_or_info（）截图过来，我怀疑你的代码有问题

**Comment by Gaylone** [comment]
用截图的

**Comment by ccjk45415** [comment]
> 用截图的

![image](https://user-images.githubusercontent.com/76248184/144699140-9d639285-ead0-45a7-af3d-2b480d2eaac9.png)
![image](https://user-images.githubusercontent.com/76248184/144699167-6594705d-639a-4fef-8287-d9c8753f61d3.png)

**Comment by Gaylone** [comment]
挺奇怪的，没毛病啊，要不你MessageSegment()外面再包一层str()试试，你是什么版本的Python

**Comment by ccjk45415** [comment]
> 挺奇怪的，没毛病啊，要不你MessageSegment()外面再包一层str()试试，你是什么版本的Python

办吧python-3.8.5-amd64

**Comment by ccjk45415** [comment]
> 挺奇怪的，没毛病啊，要不你MessageSegment()外面再包一层str()试试，你是什么版本的Python

版本 python-3.8.5-amd64

**Comment by ccjk45415** [comment]
> 挺奇怪的，没毛病啊，要不你MessageSegment()外面再包一层str()试试，你是什么版本的Python

用了你这种方法 解决了 谢谢你！

**Comment by Gaylone** [comment]
你好怪啊.jpg

**Comment by ccjk45415** [comment]
你可以把这个问题弄到文档里面吗 防止有人和我出现一样问题

> 你好怪啊.jpg
