### ISSUE TITLE
azurapi_data缺少names.json

### ISSUE THREAD

**Issue by Guanchang3** [Gaylone/blhx_wiki#7]
[2021-09-30 15:51:35,005 blhx_wiki] INFO: Message 708165484 triggered send_ship_skin_or_info by PrefixTrigger.
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/modules/blhx_wiki/__init__.py", line 67, in send_ship_skin_or_info
    ship_nickname_data = await GetIDByNickname(ship_name)
  File "/root/HoshinoBot/hoshino/modules/blhx_wiki/names.py", line 139, in GetIDByNickname
    async with aiofiles.open(PATH + '/azurapi_data/names.json', 'r', encoding='utf-8') as fp:
  File "/usr/local/lib/python3.8/site-packages/aiofiles/base.py", line 75, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/blhx_wiki/azurapi_data/names.json'

求大佬帮助，谢谢

**Comment by Guanchang3** [comment]
找不到大佬的联系方式，先留个爪，Q1076628425

**Comment by Gaylone** [comment]
你好鸭，names.json在第一次使用时，发送 blhx 强制更新 后 待更新完成后自动生成

**Comment by Guanchang3** [comment]
[2021-09-30 16:01:48,890 blhx_wiki] INFO: Message -1985478830 triggered force_update by PrefixTrigger.
命令确认，正在删除

之后就卡住了，在___init___.py的line:142和line:144出现的force_update_offline()好像没有找到呀

**Comment by Gaylone** [comment]
卡住了是因为正在从git下载json，如果你的网络环境不太好他就会卡很久，已经为这下载配置了代理了自寻azurAPI.py，理论上会卡但是不会卡很久 卡很久的话就是你网络有点问题，耐心等等吧
