### ISSUE TITLE
[Errno 13] Permission denied: '/root/HoshinoBot/hoshino/modules/blhx_wiki/wkhtmltopdf/bin/wkhtmltoimage.exe'

### ISSUE THREAD

**Issue by Guanchang3** [Gaylone/blhx_wiki#8]
wkhtml工具调用错误，错误信息如下：
------------------------------------------------------------------------
[2021-10-30 15:37:53,646 nonebot] INFO: Self:xxx, Message 1051136580 from xxx@[群xxx]: 'blhx 长门 原皮'
[2021-10-30 15:37:53,647 blhx_wiki] INFO: Message 1051136580 triggered send_ship_skin_or_info by PrefixTrigger.
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/modules/blhx_wiki/__init__.py", line 56, in send_ship_skin_or_info
    print_img_skin()
  File "/root/HoshinoBot/hoshino/modules/blhx_wiki/tools.py", line 73, in print_img_skin
    imgkit.from_file(os.path.abspath(os.path.join(SAVE_PATH, 'ship_html', 'ship_skin.html')),
  File "/usr/local/lib/python3.8/site-packages/imgkit/api.py", line 72, in from_file
    return rtn.to_img(output_path)
  File "/usr/local/lib/python3.8/site-packages/imgkit/imgkit.py", line 221, in to_img
    result = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/root/HoshinoBot/hoshino/modules/blhx_wiki/wkhtmltopdf/bin/wkhtmltoimage.exe'
------------------------------------------------------------------------

其实是因为linux通过rom方式安装了wkhtmltox-0.12.6-1.centos7.x86_64.rpm之后，tools.py里面依然是去找exe了

将tools.py中的tool_path改为'/usr/local/bin/wkhtmltoimage'，重启hoshino，成功！

请大佬指正~！

**Comment by Gaylone** [comment]
没啥问题能用就行，因为我也没在linux上跑过
